# Cau 1

## 1. a

Import các thư viện cần thiết

In [1]:
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import StandardScaler, KBinsDiscretizer
from sklearn.decomposition import PCA


Đọc dữ liệu từ file

Vì tên columns theo mô tả trong file arrhythmia.names quá phức tạp nên em sẽ tự đặt tên cho các columns , việc này không ảnh hưởng gì đến yêu cầu đề bài

In [2]:
cols_name1 = [f'Name{i}' for i in range(1, 281)]
URL_data = r'https://archive.ics.uci.edu/ml/machine-learning-databases/arrhythmia/arrhythmia.data'
data1 = pd.read_csv(URL_data, names=cols_name1)
data1.head(10)


Name1  Name2  Name3  Name4  Name5  Name6  Name7  Name8  Name9  Name10  ...  \
0     75      0    190     80     91    193    371    174    121     -16  ...   
1     56      1    165     64     81    174    401    149     39      25  ...   
2     54      0    172     95    138    163    386    185    102      96  ...   
3     55      0    175     94    100    202    380    179    143      28  ...   
4     75      0    190     80     88    181    360    177    103     -16  ...   
5     13      0    169     51    100    167    321    174     91     107  ...   
6     40      1    160     52     77    129    377    133     77      77  ...   
7     49      1    162     54     78      0    376    157     70      67  ...   
8     44      0    168     56     84    118    354    160     63      61  ...   
9     50      1    167     67     89    130    383    156     73      85  ...   

  Name271 Name272 Name273 Name274 Name275  Name276  Name277  Name278  Name279  \
0     0.0     9.0    -0.9     0.0     0.0      0.9      2.9     23.3     49.4   
1     0.0     8.5     0.0     0.0     0.0      0.2      2.1     20.4     38.8   
2     0.0     9.5    -2.4     0.0     0.0      0.3      3.4     12.3     49.0   
3     0.0    12.2    -2.2     0.0     0.0      0.4      2.6     34.6     61.6   
4     0.0    13.1    -3.6     0.0     0.0     -0.1      3.9     25.4     62.8   
5    -0.6    12.2    -2.8     0.0     0.0      0.9      2.2     13.5     31.1   
6     0.0     6.5     0.0     0.0     0.0      0.4      1.0     14.3     20.5   
7     0.0     8.2    -1.9     0.0     0.0      0.1      0.5     15.8     19.8   
8     0.0     7.0    -1.3     0.0     0.0      0.6      2.1     12.5     30.9   
9    -0.6    10.8    -1.7     0.0     0.0      0.8      0.9     20.1     25.1   

   Name280  
0        8  
1        6  
2       10  
3        1  
4        7  
5       14  
6        1  
7        1  
8        1  
9       10  

[10 rows x 280 columns]

Tổng quan bộ dữ liệu

In [3]:
display(data1.shape)
display(data1.describe())


(452, 280)

Name1       Name2       Name3       Name4       Name5       Name6  \
count  452.000000  452.000000  452.000000  452.000000  452.000000  452.000000   
mean    46.471239    0.550885  166.188053   68.170354   88.920354  155.152655   
std     16.466631    0.497955   37.170340   16.590803   15.364394   44.842283   
min      0.000000    0.000000  105.000000    6.000000   55.000000    0.000000   
25%     36.000000    0.000000  160.000000   59.000000   80.000000  142.000000   
50%     47.000000    1.000000  164.000000   68.000000   86.000000  157.000000   
75%     58.000000    1.000000  170.000000   79.000000   94.000000  175.000000   
max     83.000000    1.000000  780.000000  176.000000  188.000000  524.000000   

            Name7       Name8       Name9      Name10  ...     Name271  \
count  452.000000  452.000000  452.000000  452.000000  ...  452.000000   
mean   367.207965  169.949115   90.004425   33.676991  ...   -0.278982   
std     33.385421   35.633072   25.826643   45.431434  ...    0.548876   
min    232.000000  108.000000    0.000000 -172.000000  ...   -4.100000   
25%    350.000000  148.000000   79.000000    3.750000  ...   -0.425000   
50%    367.000000  162.000000   91.000000   40.000000  ...    0.000000   
75%    384.000000  179.000000  102.000000   66.000000  ...    0.000000   
max    509.000000  381.000000  205.000000  169.000000  ...    0.000000   

          Name272     Name273     Name274  Name275     Name276     Name277  \
count  452.000000  452.000000  452.000000    452.0  452.000000  452.000000   
mean     9.048009   -1.457301    0.003982      0.0    0.514823    1.222345   
std      3.472862    2.002430    0.050118      0.0    0.347531    1.426052   
min      0.000000  -28.600000    0.000000      0.0   -0.800000   -6.000000   
25%      6.600000   -2.100000    0.000000      0.0    0.400000    0.500000   
50%      8.800000   -1.100000    0.000000      0.0    0.500000    1.350000   
75%     11.200000    0.000000    0.000000      0.0    0.700000    2.100000   
max     23.600000    0.000000    0.800000      0.0    2.400000    6.000000   

          Name278     Name279     Name280  
count  452.000000  452.000000  452.000000  
mean    19.326106   29.473230    3.880531  
std     13.503922   18.493927    4.407097  
min    -44.200000  -38.600000    1.000000  
25%     11.450000   17.550000    1.000000  
50%     18.100000   27.900000    1.000000  
75%     25.825000   41.125000    6.000000  
max     88.800000  115.900000   16.000000  

[8 rows x 275 columns]

Kiểm tra giá trị null

In [4]:
data1.isnull().sum().sort_values(ascending=False)


Name1      0
Name185    0
Name191    0
Name190    0
Name189    0
          ..
Name100    0
Name101    0
Name102    0
Name103    0
Name280    0
Length: 280, dtype: int64

Kiểm tra  data có giá trị ? hay không

In [5]:
(data1 == '?').any().value_counts()


False    275
True       5
dtype: int64

Thay giá trị '?' thành giá trị 0, vì nếu thay thành NaN thì sẽ không dùng KBinsDiscretizer được

In [6]:
data1.replace('?', 0, inplace=True)


## 1. b

StandardScaler là hàm dùng để scale data bằng cách trừ trung bình (mean) và chia độ lệch chuẩn (standard deviation)
$$ z=\frac{x-\mu}{\sigma} $$
Dữ liệu sau khi đã scale bằng StandardScaler

In [7]:
standard_scaler = StandardScaler()
standard_scaler_data = standard_scaler.fit_transform(data1)
standard_scaler_data


array([[ 1.73443926, -1.1075202 ,  0.64132669, ...,  0.29460309,
         1.07867028,  0.93577103],
       [ 0.57931213,  0.90291807, -0.03199781, ...,  0.0796127 ,
         0.50487408,  0.4814547 ],
       [ 0.4577198 , -1.1075202 ,  0.15653305, ..., -0.52087767,
         1.0570176 ,  1.39008736],
       ...,
       [-0.63661117, -1.1075202 , -0.00506483, ..., -4.7094834 ,
        -3.3926096 , -0.42717797],
       [-0.87979583,  0.90291807, -0.30132761, ...,  0.42063193,
         0.92710147, -0.65433613],
       [ 1.91682776,  0.90291807, -0.16666271, ...,  0.14633386,
         0.18008377, -0.65433613]])

## 1. c

Hàm KBinsDiscretizer cho phép rời rạc hóa thuộc tính liên tục thành k khoảng với strategy :
- uniform : tất cả các khoảng đều có độ dài bằng nhau (tương ứng với equi_width)
- quantile : tất cả các khoảng đều có đều sô lượng phần tử giống nhau (tương ứng với equi_depth)

### Equi_width_ranges

In [8]:
equi_width_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='uniform')
equi_width_data = equi_width_scaler.fit_transform(data1)
equi_width_data


c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 19 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 67 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 69 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 83 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 131 is constant and will be replaced with 0.
  warnings.warn(
c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 132 

array([[9., 0., 1., ..., 5., 5., 4.],
       [6., 9., 0., ..., 4., 5., 3.],
       [6., 0., 0., ..., 4., 5., 6.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [3., 9., 0., ..., 5., 5., 0.],
       [9., 9., 0., ..., 4., 4., 0.]])

Xuất hiện warning vì có các cột chỉ toàn giá trị 0, tìm tất cả các cột chỉ chứa toàn giá trị 0, ta có thể tìm các cột có toàn giá trị 0 và drop thử, sau đó chạy lại

In [9]:
# Các cột có toàn giá trị 0
cols_all_zeros = data1.columns[(data1 == 0).all()]
data1.drop(labels=cols_all_zeros, inplace=True, axis=1)


In [10]:
# Chạy lại sau khi đã drop tất cả các cột chỉ chứa toàn 0
equi_width_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='uniform')
equi_width_data = equi_width_scaler.fit_transform(data1)
equi_width_data


array([[9., 0., 1., ..., 5., 5., 4.],
       [6., 9., 0., ..., 4., 5., 3.],
       [6., 0., 0., ..., 4., 5., 6.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [3., 9., 0., ..., 5., 5., 0.],
       [9., 9., 0., ..., 4., 4., 0.]])

### Equi_depth_ranges

In [11]:
equi_depth_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='quantile')
equi_depth_data = equi_width_scaler.fit_transform(data1)
equi_depth_data


array([[9., 0., 1., ..., 5., 5., 4.],
       [6., 9., 0., ..., 4., 5., 3.],
       [6., 0., 0., ..., 4., 5., 6.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [3., 9., 0., ..., 5., 5., 0.],
       [9., 9., 0., ..., 4., 4., 0.]])

# 2.

Vì bộ dữ liệu Musk data chứa file nén winrar nên không thể đọc trực tiếp mà phải tải bộ dữ liệu về máy rồi giải nén

Lấy dữ liệu columns name trong file clean1.names


In [12]:
cols_name = ['molecule_name', 'conformation_name',
             *[f'f{i}' for i in range(1, 167)], 'class']


Đọc dữ liệu từ file clean1.data, columns name là cols_name

In [13]:
data2 = pd.read_csv(
    r'C:\Users\votua\Desktop\DATA MINING\W1\DATA\clean1.data', names=cols_name)

# data2 = pd.read_csv('clean1.data')

Tổng quan bộ dữ liệu

In [14]:
display(data2.describe())
display(data2.head(10))
display(data2.dtypes)


f1          f2          f3          f4          f5          f6  \
count  476.000000  476.000000  476.000000  476.000000  476.000000  476.000000   
mean    38.731092 -120.142857  -79.243697   15.903361 -112.298319   -9.760504   
std     18.087948   88.313464   69.172519   75.515959   28.704947   92.025496   
min     -9.000000 -199.000000 -166.000000 -115.000000 -117.000000 -184.000000   
25%     31.000000 -193.000000 -144.000000  -53.000000 -117.000000  -89.000000   
50%     42.000000 -144.500000 -108.000000   28.000000 -117.000000   11.000000   
75%     50.000000 -101.000000  -21.000000   38.000000 -117.000000   70.250000   
max    130.000000   98.000000   83.000000  157.000000  238.000000  200.000000   

               f7          f8          f9         f10  ...        f158  \
count  476.000000  476.000000  476.000000  476.000000  ...  476.000000   
mean   -16.628151    7.762605  -91.048319  -76.077731  ... -204.405462   
std    106.560891   75.786461   96.321303   72.467693  ...   89.566426   
min   -170.000000 -231.000000 -242.000000 -284.000000  ... -324.000000   
25%   -159.000000   -9.250000 -215.000000 -118.250000  ... -264.000000   
50%     41.000000   18.000000  -41.000000  -73.500000  ... -236.000000   
75%     51.000000   57.000000  -30.000000  -28.000000  ... -154.750000   
max    214.000000  188.000000  135.000000  218.000000  ...   72.000000   

             f159        f160        f161        f162        f163        f164  \
count  476.000000  476.000000  476.000000  476.000000  476.000000  476.000000   
mean  -108.262605  -25.231092   37.428571   79.752101   85.363445  -34.128151   
std    121.794583   65.588295   87.315888   49.269244   47.487575   16.019277   
min   -217.000000 -135.000000 -126.000000  -78.000000   35.000000 -132.000000   
25%   -208.000000  -91.000000  -39.250000   33.000000   54.000000  -42.250000   
50%   -189.500000  -15.000000   31.500000   84.000000   69.000000  -36.000000   
75%     30.000000   22.000000  128.000000  119.000000   99.000000  -28.000000   
max    173.000000  185.000000  253.000000  291.000000  302.000000   24.000000   

             f165        f166       class  
count  476.000000  476.000000  476.000000  
mean   -26.241597   33.714286    0.434874  
std     58.009205   54.189087    0.496262  
min   -258.000000  -72.000000    0.000000  
25%    -28.000000  -12.000000    0.000000  
50%    -11.000000   35.000000    0.000000  
75%      7.000000   74.000000    1.000000  
max     82.000000  235.000000    1.000000  

[8 rows x 167 columns]

molecule_name conformation_name  f1   f2   f3  f4   f5  f6  f7   f8  ...  \
0      MUSK-188           188_1+1  42 -198 -109 -75 -117  11  23  -88  ...   
1      MUSK-188           188_1+2  42 -191 -142 -65 -117  55  49 -170  ...   
2      MUSK-188           188_1+3  42 -191 -142 -75 -117  11  49 -161  ...   
3      MUSK-188           188_1+4  42 -198 -110 -65 -117  55  23  -95  ...   
4      MUSK-190           190_1+1  42 -198 -102 -75 -117  10  24  -87  ...   
5      MUSK-190           190_1+2  42 -191 -142 -65 -117  55  49 -170  ...   
6      MUSK-190           190_1+3  42 -190 -142 -75 -117  12  49 -161  ...   
7      MUSK-190           190_1+4  42 -199 -102 -65 -117  55  23  -94  ...   
8      MUSK-211           211_1+1  40 -173 -142  13 -116  -7  50 -171  ...   
9      MUSK-211           211_1+2  44 -159  -63 -74 -117  17   5 -114  ...   

   f158  f159  f160  f161  f162  f163  f164  f165  f166  class  
0   -74  -129  -120   -38    30    48   -37     6    30    1.0  
1  -302    60  -120   -39    31    48   -37     5    30    1.0  
2   -73  -127  -120   -38    30    48   -37     5    31    1.0  
3  -302    60  -120   -39    30    48   -37     6    30    1.0  
4   -73  -127    51   128   144    43   -30    14    26    1.0  
5  -300    61    51   127   143    42   -31    14    26    1.0  
6   -72  -125    51   124   143    44   -30    14    29    1.0  
7  -300    61    51   127   144    42   -30    14    25    1.0  
8   -53    20    38    88   133    66   -28    13    58    1.0  
9   -62  -111   -12   153   134    45   -37    -9   -25    1.0  

[10 rows x 169 columns]

molecule_name         object
conformation_name     object
f1                     int64
f2                     int64
f3                     int64
                      ...   
f163                   int64
f164                   int64
f165                   int64
f166                   int64
class                float64
Length: 169, dtype: object

Kiểm tra giá trị null 

In [15]:
data2.isnull().sum().sort_values(ascending=False)


molecule_name    0
f115             0
f107             0
f108             0
f109             0
                ..
f57              0
f58              0
f59              0
f60              0
class            0
Length: 169, dtype: int64

Kiểm tra giá trị ? 

In [16]:
((data2 == '?') == True).sum().sort_values(ascending=False)


molecule_name    0
f115             0
f107             0
f108             0
f109             0
                ..
f57              0
f58              0
f59              0
f60              0
class            0
Length: 169, dtype: int64

Vì cột molecule_name và cột conformation_name có kiểu chuỗi(dtypes là object) nên để xử lý pca thì ta phải xóa 2 cột đó ra, cũng như xóa cột class vì nó là label cần dự đoán

In [17]:
# Xoa kieu object
data2_pca = data2.select_dtypes(exclude='object')

# Xoa cot label
data2_pca = data2_pca[data2_pca.columns[:-1]]
data2_pca


f1   f2   f3   f4   f5   f6   f7   f8   f9  f10  ...  f157  f158  f159  \
0    42 -198 -109  -75 -117   11   23  -88  -28  -27  ...  -238   -74  -129   
1    42 -191 -142  -65 -117   55   49 -170  -45    5  ...  -238  -302    60   
2    42 -191 -142  -75 -117   11   49 -161  -45  -28  ...  -238   -73  -127   
3    42 -198 -110  -65 -117   55   23  -95  -28    5  ...  -238  -302    60   
4    42 -198 -102  -75 -117   10   24  -87  -28  -28  ...  -238   -73  -127   
..   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
471  49 -199 -161   29  -95  -86  -48    2  112  -79  ...  -220  -246  -209   
472  38 -123 -139   30 -117  -88  214  -13  -74 -129  ...  -236  -226  -210   
473  43 -102  -20 -101 -116  200 -166   66 -222  -49  ...   114    32   136   
474  39  -58   27   31 -117  -92   85   21  -73  -68  ...  -228  -232  -206   
475  52 -121  -24 -104 -116  195 -162   76 -226  -56  ...    99    34   133   

     f160  f161  f162  f163  f164  f165  f166  
0    -120   -38    30    48   -37     6    30  
1    -120   -39    31    48   -37     5    30  
2    -120   -38    30    48   -37     5    31  
3    -120   -39    30    48   -37     6    30  
4      51   128   144    43   -30    14    26  
..    ...   ...   ...   ...   ...   ...   ...  
471    33   152   134    47   -43   -15   -10  
472    20    55   119    79   -28     4    74  
473   -15   143   121    55   -37   -19   -36  
474    13    45   116    79   -28     3    74  
475   -20   -46    95    98   -14    12    96  

[476 rows x 166 columns]

## 2.1 PCA sử dụng Hàm PCA trong thư viện sklearn

Sử dụng tham số mặc định của hàm PCA : 
- n_components : số lượng components muốn giữ lại , nếu không set thì sẽ giữ lại tất cả 
- svd_solver : auto , PCA sẽ tự động dùng phương pháp nào tối ưu nhất
- ...

Một số attributes của hàm PCA :
- components_ : Principal axes trong feature space , tương ứng với hướng làm cho variance lớn nhất , sắp xếp giảm dần theo explained_variance_
- explained_variance_ : số lượng variance mà mỗi components capture được , bằng với eigenvalues của ma trận hiệp phương sai (sắp xếp giảm dần)
- explained_variance_ratio_ : giống explained_varinace_ nhưng ở dạng %
- singular_values : singular values của phép biến đổi svd trên data(đã centered)
- ...

In [18]:
pca = PCA()
pca.fit(data2_pca)


PCA()

Eigen Vectors ở đây là attribute components_ của PCA, và là Principal axes trong feature space, mỗi dòng của ma trận components_ tương ứng với 1 Principal Axis

In [19]:
eigen_vectors = pca.components_
eigen_vectors

array([[ 6.07485616e-03,  5.91429272e-02,  6.62868505e-02, ...,
         8.49513583e-06,  1.59190184e-03, -7.30081669e-03],
       [ 5.92762401e-04,  2.37599858e-02,  1.79219018e-03, ...,
        -5.05151914e-03, -1.69781919e-02,  7.01984258e-03],
       [-2.15462256e-02, -2.07846004e-01, -1.30939223e-01, ...,
        -3.66054356e-04, -1.94359625e-02, -5.28802497e-02],
       ...,
       [-1.96796955e-02, -3.79872287e-02, -1.20048201e-01, ...,
        -2.84987143e-02,  6.37283820e-03,  1.00611934e-02],
       [-4.47315337e-03, -4.06566237e-02, -8.82095314e-02, ...,
        -1.58940591e-02, -3.10577822e-02,  3.44633055e-02],
       [-2.23488843e-02, -3.10853790e-04, -8.35723864e-03, ...,
        -4.78260535e-04, -4.77572051e-03,  7.35520907e-03]])

Eigen Values ở đây là bình phương của attribute singular_values_ của PCA, vì hàm PCA của sklearn dùng svd để tính

In [20]:
eigen_values = np.square(pca.singular_values_)
eigen_values


array([2.15288802e+08, 6.87580606e+07, 3.69600481e+07, 2.96094501e+07,
       2.33120755e+07, 2.21928596e+07, 1.45721304e+07, 1.12142336e+07,
       8.63229343e+06, 8.19110874e+06, 6.73478194e+06, 6.11955264e+06,
       5.83902176e+06, 4.69007934e+06, 4.34051303e+06, 4.06601261e+06,
       3.60899999e+06, 3.37731459e+06, 3.23202241e+06, 2.99697311e+06,
       2.80182188e+06, 2.58777821e+06, 2.48234992e+06, 2.28328607e+06,
       2.02958029e+06, 1.94750071e+06, 1.80329388e+06, 1.73547559e+06,
       1.62726768e+06, 1.48793251e+06, 1.40129766e+06, 1.27848796e+06,
       1.17817363e+06, 1.15305171e+06, 1.11086572e+06, 1.00320354e+06,
       9.51483791e+05, 8.73556883e+05, 8.29563979e+05, 7.68594160e+05,
       7.41062189e+05, 6.79964559e+05, 6.53585453e+05, 6.18406082e+05,
       5.61214822e+05, 5.41665466e+05, 5.07152642e+05, 4.72007399e+05,
       4.65572872e+05, 4.35927998e+05, 4.12735506e+05, 3.86644555e+05,
       3.76253591e+05, 3.63981102e+05, 3.54812883e+05, 3.44759644e+05,
      

## 2.2 PCA sử dụng phân tích SVD 

Center data về gốc tọa độ

In [21]:
n, p = data2_pca.shape
xbar = np.array(data2_pca-np.mean(data2_pca, axis=0))
xbar


array([[  3.26890756, -77.85714286, -29.75630252, ...,  -2.87184874,
         32.24159664,  -3.71428571],
       [  3.26890756, -70.85714286, -62.75630252, ...,  -2.87184874,
         31.24159664,  -3.71428571],
       [  3.26890756, -70.85714286, -62.75630252, ...,  -2.87184874,
         31.24159664,  -2.71428571],
       ...,
       [  4.26890756,  18.14285714,  59.24369748, ...,  -2.87184874,
          7.24159664, -69.71428571],
       [  0.26890756,  62.14285714, 106.24369748, ...,   6.12815126,
         29.24159664,  40.28571429],
       [ 13.26890756,  -0.85714286,  55.24369748, ...,  20.12815126,
         38.24159664,  62.28571429]])

Phân tích SVD của ma trận Xbar 
$$ \bar{X} = U\Sigma V^T $$
Ở đây V chính là Principle Axis trong feature space = Components_ của Hàm PCA 

In [22]:
U, S, VT = np.linalg.svd(xbar)


Kiểm tra so với kết quả của hàm PCA trong thư viện sklearn

Hàm numpy.allclose sẽ so sánh từng cặp giá trị (element-wise), trả về True nếu tất cả đều bằng nhau

Vì dấu của eigen vectors của PCA và dấu của eigen vector tự tính có thể không giống nhau nên em sẽ dùng numpy.abs để kiểm tra. [reference](https://math.stackexchange.com/questions/2359992/how-to-resolve-the-sign-issue-in-a-svd-problem)

In [23]:
# Kiem tra eigen vectors
print(np.allclose(np.abs(VT.T), np.abs(eigen_vectors.T)))
# Kiem tra eigen values
print(np.allclose(np.square(S), eigen_values))


True
True


## 2.3 PCA sử dụng Eigen decomposition 

Dùng eigen decompositon cho ma trận hiệp phương sai 
$$ C = \frac{1}{n-1}\bar{X}^T \bar{X} = P\Lambda P^T $$

P = V trong 2.2 = components_ trong 2.1

In [24]:
# Eigen Decomposition cho ma tran hiep phuong sai
Lambda, P = np.linalg.eig(np.cov(xbar, rowvar=False))
# Sort theo thứ tự giảm dần của eigen values
idx = Lambda.argsort()[::-1]
Lambda, P = Lambda[idx], P[:, idx]


Ta có : 
\begin{align}
C &= \frac{1}{n-1}\bar{X}^T \bar{X} =P\Lambda P^T\\
&= \frac{1}{n-1}(U\Sigma V^T)^T(U\Sigma V^T) \\
&= \frac{1}{n-1}V\Sigma U^T U\Sigma V^T \\
&= \frac{1}{n-1}V\Sigma^2V^T \\
&\Rightarrow \Lambda*(n-1)=\Sigma^2
\end{align}


Kiểm tra với hàm pca trong thư viện sklearn

In [25]:

print(np.allclose(np.abs(P), np.abs(eigen_vectors.T)))
print(np.allclose(Lambda,pca.explained_variance_))
print(np.allclose((Lambda*(n-1)), eigen_values))


True
True
True
