# Câu 1 

In [262]:
import pandas as pd
import numpy as np

Đọc dữ liệu từ file

In [263]:
URL=r'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data' # raw string
df1=pd.read_csv(URL,header=None)
df1.head(10)

0   1        2        3        4        5        6        7        8   \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
5   1   0  0.02337 -0.00592 -0.09924 -0.11949 -0.00763 -0.11824  0.14706   
6   1   0  0.97588 -0.10602  0.94601 -0.20800  0.92806 -0.28350  0.85996   
7   0   0  0.00000  0.00000  0.00000  0.00000  1.00000 -1.00000  0.00000   
8   1   0  0.96355 -0.07198  1.00000 -0.14333  1.00000 -0.21313  1.00000   
9   1   0 -0.01864 -0.08459  0.00000  0.00000  0.00000  0.00000  0.11470   

        9   ...       25       26       27       28       29       30  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   
5  0.06637  ... -0.01535 -0.03240  0.09223 -0.07859  0.00732  0.00000   
6 -0.27342  ... -0.81634  0.13659 -0.82510  0.04606 -0.82395 -0.04262   
7  0.00000  ...  1.00000  1.00000  1.00000  0.00000  0.00000  1.00000   
8 -0.36174  ... -0.65440  0.57577 -0.69712  0.25435 -0.63919  0.45114   
9 -0.26810  ... -0.01326  0.20645 -0.02294  0.00000  0.00000  0.16595   

        31       32       33  34  
0 -0.54487  0.18641 -0.45300   g  
1 -0.06288 -0.13738 -0.02447   b  
2 -0.24180  0.56045 -0.38238   g  
3  1.00000 -0.32382  1.00000   b  
4 -0.59573 -0.04608 -0.65697   g  
5  0.00000 -0.00039  0.12011   b  
6 -0.81318 -0.13832 -0.80975   g  
7  1.00000  0.00000  0.00000   b  
8 -0.72779  0.38895 -0.73420   g  
9  0.24086 -0.08208  0.38065   b  

[10 rows x 35 columns]

Tổng quan bộ dữ liệu

In [264]:
display(df1.info())
display(df1.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       351 non-null    int64  
 1   1       351 non-null    int64  
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22

None

0      1           2           3           4           5   \
count  351.000000  351.0  351.000000  351.000000  351.000000  351.000000   
mean     0.891738    0.0    0.641342    0.044372    0.601068    0.115889   
std      0.311155    0.0    0.497708    0.441435    0.519862    0.460810   
min      0.000000    0.0   -1.000000   -1.000000   -1.000000   -1.000000   
25%      1.000000    0.0    0.472135   -0.064735    0.412660   -0.024795   
50%      1.000000    0.0    0.871110    0.016310    0.809200    0.022800   
75%      1.000000    0.0    1.000000    0.194185    1.000000    0.334655   
max      1.000000    0.0    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9   ...          24  \
count  351.000000  351.000000  351.000000  351.000000  ...  351.000000   
mean     0.550095    0.119360    0.511848    0.181345  ...    0.396135   
std      0.492654    0.520750    0.507066    0.483851  ...    0.578451   
min     -1.000000   -1.000000   -1.000000   -1.000000  ...   -1.000000   
25%      0.211310   -0.054840    0.087110   -0.048075  ...    0.000000   
50%      0.728730    0.014710    0.684210    0.018290  ...    0.553890   
75%      0.969240    0.445675    0.953240    0.534195  ...    0.905240   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

               25          26          27          28          29          30  \
count  351.000000  351.000000  351.000000  351.000000  351.000000  351.000000   
mean    -0.071187    0.541641   -0.069538    0.378445   -0.027907    0.352514   
std      0.508495    0.516205    0.550025    0.575886    0.507974    0.571483   
min     -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   
25%     -0.332390    0.286435   -0.443165    0.000000   -0.236885    0.000000   
50%     -0.015050    0.708240   -0.017690    0.496640    0.000000    0.442770   
75%      0.156765    0.999945    0.153535    0.883465    0.154075    0.857620   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               31          32          33  
count  351.000000  351.000000  351.000000  
mean    -0.003794    0.349364    0.014480  
std      0.513574    0.522663    0.468337  
min     -1.000000   -1.000000   -1.000000  
25%     -0.242595    0.000000   -0.165350  
50%      0.000000    0.409560    0.000000  
75%      0.200120    0.813765    0.171660  
max      1.000000    1.000000    1.000000  

[8 rows x 34 columns]

Vì cột cuối là string (có dtype là object) nên mình sẽ drop đi để xử lý

In [265]:
df1.drop(df1.columns[-1],inplace=True, axis=1)
df1.head(10)

0   1        2        3        4        5        6        7        8   \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
5   1   0  0.02337 -0.00592 -0.09924 -0.11949 -0.00763 -0.11824  0.14706   
6   1   0  0.97588 -0.10602  0.94601 -0.20800  0.92806 -0.28350  0.85996   
7   0   0  0.00000  0.00000  0.00000  0.00000  1.00000 -1.00000  0.00000   
8   1   0  0.96355 -0.07198  1.00000 -0.14333  1.00000 -0.21313  1.00000   
9   1   0 -0.01864 -0.08459  0.00000  0.00000  0.00000  0.00000  0.11470   

        9   ...       24       25       26       27       28       29  \
0  0.03760  ...  0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.34090   
1 -0.04549  ... -0.20332 -0.26569 -0.20468 -0.18401 -0.19040 -0.11593   
2  0.01198  ...  0.57528 -0.40220  0.58984 -0.22145  0.43100 -0.17365   
3  0.00000  ...  1.00000  0.90695  0.51613  1.00000  1.00000 -0.20099   
4 -0.16399  ...  0.03286 -0.65158  0.13290 -0.53206  0.02431 -0.62197   
5  0.06637  ...  0.03513 -0.01535 -0.03240  0.09223 -0.07859  0.00732   
6 -0.27342  ...  0.22792 -0.81634  0.13659 -0.82510  0.04606 -0.82395   
7  0.00000  ...  1.00000  1.00000  1.00000  1.00000  0.00000  0.00000   
8 -0.36174  ...  0.85106 -0.65440  0.57577 -0.69712  0.25435 -0.63919   
9 -0.26810  ... -0.14803 -0.01326  0.20645 -0.02294  0.00000  0.00000   

        30       31       32       33  
0  0.42267 -0.54487  0.18641 -0.45300  
1 -0.16626 -0.06288 -0.13738 -0.02447  
2  0.60436 -0.24180  0.56045 -0.38238  
3  0.25682  1.00000 -0.32382  1.00000  
4 -0.05707 -0.59573 -0.04608 -0.65697  
5  0.00000  0.00000 -0.00039  0.12011  
6 -0.04262 -0.81318 -0.13832 -0.80975  
7  1.00000  1.00000  0.00000  0.00000  
8  0.45114 -0.72779  0.38895 -0.73420  
9  0.16595  0.24086 -0.08208  0.38065  

[10 rows x 34 columns]

## Tính chuẩn 1 cho từng cặp dữ liệu (theo cột)

Hàm pdist cho phép tính khoảng cách giữa các cặp điểm trong một mảng đa chiều, pdist được cài đặt hiệu quả để tính toán khoảng cách giữa các cặp điểm một cách nhanh chóng, đặc biệt đối với các mảng dữ liệu lớn

Hàm squareform sẽ chuyển đổi mảng 1D chứa khoảng cách giữa các cặp điểm (mảng được sinh ra từ hàm pdist) thành ma trận đầy đủ , trong đó giá trị tại hàng i và cột j của ma trận là giá trị khoảng cách giữa cặp điểm i và j trong mảng 1D ban đầu

In [266]:
from scipy.spatial import distance

# Tính ma trận khoảng cách chuẩn 1 (l1 norm) bằng hàm pdist trong thư viện scipy
# Em sẽ không tự code hàm tính khoảng cách cho từng cặp điểm vì với dữ liệu lớn thì dùng hàm có sắn của thư viện (code trên ngôn ngữ C) sẽ hiệu năng tốt hơn rất nhiều 
norm1_distance = distance.squareform(distance.pdist((np.asarray(df1)).T, metric='cityblock'))

# norm1_distance[i,j] là khoảng cách chuẩn 1 (l1 norm) từ i đến j trong ma trận khoảng cách


Kiểm tra shape của ma trận khoảng cách , (34,34) là đúng vì có 34 cột nên sẽ có 34 khoảng cách từ 1 cột đến các cột còn lại (kể cả cột đó), và ma trận này là symmetric vì khoảng cách từ cột i đến cột j cũng bằng khoảng cách từ cột j đến cột i

In [267]:
norm1_distance.shape

(34, 34)

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

In [268]:
norm1_distance[0,1]
# Kết quả là 313.0 bằng với trong file pdf

313.0

## Chuẩn 2 cho từng cặp dữ liệu (theo cột )

In [269]:
from scipy.spatial import distance
norm2_distance=distance.squareform(distance.pdist((np.asarray(df1)).T,metric='euclidean'))

# Ma trận khoảng cách với norm2_distance[i,j] là khoảng cách từ i đến j
norm2_distance

array([[ 0.        , 17.69180601, 10.48097459, ..., 20.46909354,
        14.63557175, 19.4853142 ],
       [17.69180601,  0.        , 15.20107919, ...,  9.60835939,
        11.76661551,  8.76598594],
       [10.48097459, 15.20107919,  0.        , ..., 18.07681495,
        12.81724163, 17.35801695],
       ...,
       [20.46909354,  9.60835939, 18.07681495, ...,  0.        ,
        15.30185023,  9.08258166],
       [14.63557175, 11.76661551, 12.81724163, ..., 15.30185023,
         0.        , 15.30800196],
       [19.4853142 ,  8.76598594, 17.35801695, ...,  9.08258166,
        15.30800196,  0.        ]])

Kiểm tra shape của ma trận khoảng cách , (34,34) là đúng vì có 34 cột nên sẽ có 34 khoảng cách từ 1 cột đến các cột còn lại (kể cả cột đó), và ma trận này là symmetric vì khoảng cách từ cột i đến cột j cũng bằng khoảng cách từ cột j đến cột i

In [270]:
norm2_distance.shape

(34, 34)

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

In [271]:
norm2_distance[0,1]
# Kết quả là 17.69 bằng với trong file pdf

17.69180601295413

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

## Chuẩn vô cùng cho từng cặp dữ liệu (theo cột )

In [272]:
from scipy.spatial import distance
norm_inf_distance=distance.squareform(distance.pdist((np.asarray(df1)).T,metric='chebychev'))

# Ma trận khoảng cách với norm2_distance[i,j] là khoảng cách từ i đến j
norm_inf_distance

array([[0., 1., 2., ..., 2., 2., 2.],
       [1., 0., 1., ..., 1., 1., 1.],
       [2., 1., 0., ..., 2., 2., 2.],
       ...,
       [2., 1., 2., ..., 0., 2., 2.],
       [2., 1., 2., ..., 2., 0., 2.],
       [2., 1., 2., ..., 2., 2., 0.]])

Kiểm tra shape của ma trận khoảng cách , (34,34) là đúng vì có 34 cột nên sẽ có 34 khoảng cách từ 1 cột đến các cột còn lại (kể cả cột đó), và ma trận này là symmetric vì khoảng cách từ cột i đến cột j cũng bằng khoảng cách từ cột j đến cột i

In [273]:
norm_inf_distance.shape

(34, 34)

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

In [274]:
# Khoảng cách giữa 2 điểm 1, 2 (cột 0 và 1 )
print(norm_inf_distance[0,1])
# Kết quả là 1 bằng với trong file pdf

# Khoảng cách giữa 2 điểm 1, 3 (cột 0 và 2)
print(norm_inf_distance[0,2])
# Kết quả là 2 bằng với trong file pdf

1.0
2.0


Em sẽ tính thêm khoảng cách giữa các dòng trong dataframe, vì tính khoảng cách giữa các điểm dữ liệu nó sẽ make sense hơn là tính khoảng cách giữa các cột

In [275]:
norm1_distance = distance.squareform(distance.pdist(np.asarray(df1), metric='cityblock')) # Chuẩn 1
norm2_distance = distance.squareform(distance.pdist(np.asarray(df1), metric='euclidean')) # Chuẩn 2
norm_inf_distance = distance.squareform(distance.pdist(np.asarray(df1), metric='chebychev')) # Chuẩn vô cùng

# Câu 2

In [276]:
import numpy as np
import pandas as pd

Đọc dữ liệu từ file

In [277]:
# df2=pd.read_csv(r'C:\Users\votua\Desktop\DATA MINING\W2\DATA\kddcup.data.corrected',header=None)
df2=pd.read_csv('kddcup.data.corrected',header=None)
df2.head(10)

0    1     2   3    4      5   6   7   8   9   ...  32   33   34    35  \
0   0  tcp  http  SF  215  45076   0   0   0   0  ...   0  0.0  0.0  0.00   
1   0  tcp  http  SF  162   4528   0   0   0   0  ...   1  1.0  0.0  1.00   
2   0  tcp  http  SF  236   1228   0   0   0   0  ...   2  1.0  0.0  0.50   
3   0  tcp  http  SF  233   2032   0   0   0   0  ...   3  1.0  0.0  0.33   
4   0  tcp  http  SF  239    486   0   0   0   0  ...   4  1.0  0.0  0.25   
5   0  tcp  http  SF  238   1282   0   0   0   0  ...   5  1.0  0.0  0.20   
6   0  tcp  http  SF  235   1337   0   0   0   0  ...   6  1.0  0.0  0.17   
7   0  tcp  http  SF  234   1364   0   0   0   0  ...   7  1.0  0.0  0.14   
8   0  tcp  http  SF  239   1295   0   0   0   0  ...   8  1.0  0.0  0.12   
9   0  tcp  http  SF  181   5450   0   0   0   0  ...   9  1.0  0.0  0.11   

    36   37   38   39   40       41  
0  0.0  0.0  0.0  0.0  0.0  normal.  
1  0.0  0.0  0.0  0.0  0.0  normal.  
2  0.0  0.0  0.0  0.0  0.0  normal.  
3  0.0  0.0  0.0  0.0  0.0  normal.  
4  0.0  0.0  0.0  0.0  0.0  normal.  
5  0.0  0.0  0.0  0.0  0.0  normal.  
6  0.0  0.0  0.0  0.0  0.0  normal.  
7  0.0  0.0  0.0  0.0  0.0  normal.  
8  0.0  0.0  0.0  0.0  0.0  normal.  
9  0.0  0.0  0.0  0.0  0.0  normal.  

[10 rows x 42 columns]

Drop các cột không cần thiết

In [278]:
df2.drop(df2.columns[[1,2,3,41]],axis=1,inplace=True)
df2

0    4      5   6   7   8   9   10  11  12  ...  31   32   33   34  \
0         0  215  45076   0   0   0   0   0   1   0  ...   0    0  0.0  0.0   
1         0  162   4528   0   0   0   0   0   1   0  ...   1    1  1.0  0.0   
2         0  236   1228   0   0   0   0   0   1   0  ...   2    2  1.0  0.0   
3         0  233   2032   0   0   0   0   0   1   0  ...   3    3  1.0  0.0   
4         0  239    486   0   0   0   0   0   1   0  ...   4    4  1.0  0.0   
...      ..  ...    ...  ..  ..  ..  ..  ..  ..  ..  ...  ..  ...  ...  ...   
4898426   0  212   2288   0   0   0   0   0   1   0  ...   3  255  1.0  0.0   
4898427   0  219    236   0   0   0   0   0   1   0  ...   4  255  1.0  0.0   
4898428   0  218   3610   0   0   0   0   0   1   0  ...   5  255  1.0  0.0   
4898429   0  219   1234   0   0   0   0   0   1   0  ...   6  255  1.0  0.0   
4898430   0  219   1098   0   0   0   0   0   1   0  ...   7  255  1.0  0.0   

           35    36   37    38   39   40  
0        0.00  0.00  0.0  0.00  0.0  0.0  
1        1.00  0.00  0.0  0.00  0.0  0.0  
2        0.50  0.00  0.0  0.00  0.0  0.0  
3        0.33  0.00  0.0  0.00  0.0  0.0  
4        0.25  0.00  0.0  0.00  0.0  0.0  
...       ...   ...  ...   ...  ...  ...  
4898426  0.33  0.05  0.0  0.01  0.0  0.0  
4898427  0.25  0.05  0.0  0.01  0.0  0.0  
4898428  0.20  0.05  0.0  0.01  0.0  0.0  
4898429  0.17  0.05  0.0  0.01  0.0  0.0  
4898430  0.14  0.05  0.0  0.01  0.0  0.0  

[4898431 rows x 38 columns]

Vì để tính độ đo thích ứng (match measure) và độ đo tần suất xuất hiện ngược (inverse occurrence frequency measure) dữ liệu phải là biến category nên em sẽ rời rạc hóa các thuộc tính liên tục bằng Hàm KBinsDiscretizer

In [279]:
from sklearn.preprocessing import KBinsDiscretizer
equi_width_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='uniform')

df2_cp = equi_width_scaler.fit_transform(df2)

c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 16 is constant and will be replaced with 0.
  warnings.warn(


In [280]:
# Convert trở lại vào dataframe
# df2_cp=pd.DataFrame(df2_cp,columns=[1,2])
df2_cp=pd.DataFrame(df2_cp)
df2_cp

0    1    2    3    4    5    6    7    8    9   ...   28   29   30  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  0.0   
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4898426  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898427  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898428  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898429  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898430  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   

          31   32   33   34   35   36   37  
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1        0.0  9.0  0.0  0.0  0.0  0.0  0.0  
2        0.0  5.0  0.0  0.0  0.0  0.0  0.0  
3        0.0  3.0  0.0  0.0  0.0  0.0  0.0  
4        0.0  2.0  0.0  0.0  0.0  0.0  0.0  
...      ...  ...  ...  ...  ...  ...  ...  
4898426  0.0  3.0  0.0  0.0  0.0  0.0  0.0  
4898427  0.0  2.0  0.0  0.0  0.0  0.0  0.0  
4898428  0.0  2.0  0.0  0.0  0.0  0.0  0.0  
4898429  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
4898430  0.0  1.0  0.0  0.0  0.0  0.0  0.0  

[4898431 rows x 38 columns]

In [281]:
# Chuyển việc rời rạc hóa thành các bins là các số nguyên nên em sẽ convert df2_cp về sang số nguyên cho tối ưu
df2_cp=df2_cp.astype(dtype=np.int32)
# df2_cp.head()

Để tính inverse occurence frequency measure , cần phải tính tần xuất của mỗi giá trị trong 1 cột, nên em sẽ tạo một dictionary để lưu sẵn các giá trị đó, tránh phải tính đi lại nhiều lần dẫn đến hiện năng kém

In [282]:
value_counts_dict = {}

for i,column in enumerate(df2_cp.columns):
    value_counts_dict[i]=df2_cp[column].value_counts(normalize=True).to_dict()
value_counts_dict

{0: {0: 0.997679665182586,
  1: 0.001373092731121455,
  2: 0.000604683418016912,
  3: 0.00020006406132902556,
  4: 5.103675033903713e-05,
  6: 4.4912340298352675e-05,
  5: 2.8580580189860793e-05,
  7: 1.776078911798492e-05,
  9: 2.0414700135614854e-07},
 1: {0: 0.9999987751179918,
  5: 2.0414700135614854e-07,
  4: 2.0414700135614854e-07,
  9: 2.0414700135614854e-07,
  2: 2.0414700135614854e-07,
  1: 2.0414700135614854e-07,
  8: 2.0414700135614854e-07},
 2: {0: 0.999999387558996,
  3: 4.082940027122971e-07,
  9: 2.0414700135614854e-07},
 3: {0: 0.999994283883962, 9: 5.716116037972159e-06},
 4: {0: 0.9997472660123211,
  9: 0.00019802259131546408,
  3: 5.4711396363447806e-05},
 5: {0: 0.9999985709709905,
  1: 8.165880054245942e-07,
  3: 2.0414700135614854e-07,
  2: 2.0414700135614854e-07,
  9: 2.0414700135614854e-07},
 6: {0: 0.9995990552893366,
  2: 0.00017087104013509632,
  3: 0.00016556321809983645,
  1: 6.369386442311835e-05,
  5: 4.082940027122971e-07,
  9: 2.0414700135614854e-07,
  

In [283]:
df2_cp=np.asarray(df2_cp)

Em sẽ dùng hàm NearestNeighbors trong thư viện sklearn để tính k láng giềng gần nhất cho mỗi điểm dữ liệu, dưới đây là mô tả đơn giản về  các tham số cũng như cách sử dụng hàm NearestNeighbor em tổng hợp từ documentation của thư viện sklearn

- n_neighbors: Đây là số lượng láng giềng gần nhất cần tìm kiếm. Tham số này được đặt bằng giá trị của k, là một số nguyên dương.

- algorithm: Đây là thuật toán được sử dụng để tìm kiếm láng giềng gần nhất. Có thể lựa chọn giữa các giá trị "auto", "ball_tree", "kd_tree", hoặc "brute". Thông thường, giá trị "auto" sẽ tự động chọn thuật toán phù hợp dựa trên dữ liệu đầu vào.

- metric: Đây là hàm khoảng cách được sử dụng để tính khoảng cách giữa các điểm dữ liệu. Có thể lựa chọn giữa các hàm khoảng cách có sẵn trong sklearn hoặc tự định nghĩa hàm khoảng cách riêng. Ví dụ: 'euclidean', 'manhattan', 'minkowski', vv.

- metric_params: Đây là tham số tùy chọn được truyền vào hàm khoảng cách nếu cần thiết. Thường thì không cần thiết phải sử dụng tham số này, và để mặc định là None.

- Sau khi khởi tạo đối tượng NearestNeighbors và fit dữ liệu vào model bằng phương thức fit(), chúng ta có thể sử dụng phương thức kneighbors() để tìm kiếm láng giềng gần nhất cho một điểm dữ liệu mới (hoặc một tập điểm dữ liệu mới). Kết quả trả về gồm hai mảng: distances là khoảng cách từ điểm dữ liệu mới đến k láng giềng gần nhất, và indices là chỉ số của các láng giềng gần nhất trong tập dữ liệu huấn luyện ban đầu.

Vì độ đo match measure và inverse occurrence frequency measure là 1 simility function, tức là sẽ cho ``giá trị càng lớn nếu 2 điểm càng gần nhau``, trong khi hàm NearestNeighbors nhận vào hàm tính khoảng cách distance function (``2 điểm càng gần nhau thì khoảng cách càng thấp``), nên lúc code hàm match_measure và inverse_occurrence_frequency_measure, em sẽ lấy giá trị âm để đúng với yêu cầu của hàm NearestNeighbors.


In [284]:
# Hàm tính match measure giữa 2 vectors
def match_measure(X,Y):
    return -np.count_nonzero(X==Y)

def inverse_occurrence_frequency_measure(X, Y, value_counts_dict):
    # Tạo một mảng 1D chứa các giá trị frequency tương ứng với các phần tử trong X
    frequencies = np.array([value_counts_dict[i][x] for i, x in enumerate(X)])
    
    # Tìm các vị trí trong X và Y mà giá trị tại đó bằng nhau
    equal_indices = np.where(X == Y)
    
    # Tính tổng của nghịch đảo bình phương của các frequency tại các vị trí trên
    S = np.sum(1 / (frequencies[equal_indices] ** 2))
    
    return -S



Sử dụng hàm NearestNeighbors để tính k láng giềng gần nhất của mỗi điểm dữ liệu 

Vì dữ liệu khá lớn (~5 triệu dòng), nếu muốn tìm k láng giềng gần nhất cho mỗi điểm dữ liệu thì tương đương với việc tính 5.000.000*4.999.999/2 khoảng cách, và muốn tính mỗi khoảng cách phải loop qua tất cả các cột, tức độ phức tạp thuật toán nếu dùng cách vét cạn (brute) là O(n x n x p) hoặc O(n x log(n) x p) nếu dùng ball_tree ( với n là số dòng và p là số cột)

Với độ phức tạp thuật toán là O(n x n x p) hay O(n x log(n) x p) thì việc tính toán trên dữ liệu gần 5 triệu dòng sẽ tốn rất nhiều thời gian, nên em chỉ sẽ tính cho 1000 điểm dữ liệu đầu tiên

## Tính k láng giềng gần nhất bằng độ đo match measure 

Thuật toán em dùng để tính là ball_tree, bằng cách sử dụng ball_tree thay vì brute, việc này giảm độ phức tạp thuật toán từ O(n x n x p) xuống còn O (n x log(n) x p)


In [285]:
from sklearn.neighbors import NearestNeighbors

neighbor_match=NearestNeighbors(n_neighbors= 20,metric=match_measure,algorithm='ball_tree').fit(df2_cp[:1000,:])
# result1_arr=neighbor_match.kneighbors(df2_cp[:1000,:])
result1_arr=neighbor_match.kneighbors()


Ta có result1_arr là 1 tuple gồm 2 ma trận, với ma trận đầu tiên là khoảng cách từ mỗi điểm đến k điểm gần nhất , ma trận thứ hai tương ứng là index của các điểm gần nhất đó

In [286]:
print(result1_arr[1])
print(result1_arr[0])

[[11 19 24 ... 10  9  8]
 [ 8 20 19 ...  4  7  3]
 [ 8 20 19 ...  4  7  3]
 ...
 [19 25 15 ...  3  7  9]
 [19 25 15 ...  3  7  9]
 [27 29 32 ... 11 22 10]]
[[-37. -37. -37. ... -36. -36. -36.]
 [-37. -37. -37. ... -37. -37. -37.]
 [-37. -37. -37. ... -37. -37. -37.]
 ...
 [-37. -37. -37. ... -36. -36. -36.]
 [-37. -37. -37. ... -36. -36. -36.]
 [-37. -37. -37. ... -36. -36. -35.]]


In [287]:
print('k lang gieng gan nhat voi diem 0 : ')
print(result1_arr[1][0,:]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-result1_arr[0][0,:]) # In ra độ đo match measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 : 
[11 19 24 15 18 20 23 13 14 16 17 25 21 22 12  4  7 10  9  8]
khoang cach tuong ung
[37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 36. 36. 36.
 36. 36.]


Em sẽ kiểm tra lại bằng cách tính trực tiếp

Ở đây em chỉ kiểm tra với khoảng cách lớn nhất (37), vì ví dụ như có nhiều hơn k điểm với khoảng cách bằng nhau, thì khi lấy k điểm láng giềng có thể sẽ khác nhau

Ví dụ như có 3 điểm (1, 2, 3 ) có khoảng cách bằng nhau tới điểm 0 , thì khi lấy 2 láng giềng của điểm 0 thì có thể là (1, 2) ,(2, 3) hay (1, 3)

In [288]:
print('k lang gieng gan nhat voi diem 0 : ')
print(np.argsort(np.array([match_measure(df2_cp[0,:],df2_cp[i]) for i in range(0,1000)]))[1:21]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-np.sort(np.array([match_measure(df2_cp[0,:],df2_cp[i,:]) for i in range(0,1000)]))[1:21]) # In ra độ đo match measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 : 
[ 25  24  23  22  21  20  19  17  16  15  14  13  18  11  12 531 532 533
 534 535]
khoang cach tuong ung
[37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 36 36 36 36 36]


Kết quả kiểm tra 15 điểm gần với 0 nhất với khoảng cách là 37 là : 11 19 24 15 18 20 23 13 14 16 17 25 21 22 12

## Tính k láng giềng gần nhất bằng độ đo inverse occurence frequency measure 

Vì inverse_occurrence_frequency_measure không dùng thuật toán ball_tree được nên em chỉ sử dụng thuật toán brute thông thường với độ phức tạp O(n x n x p), nên e chỉ tính cho 1000 điểm dữ liệu đầu tiền

In [289]:
from sklearn.neighbors import NearestNeighbors

neighbor_iofm=NearestNeighbors(n_neighbors=20 ,metric=inverse_occurrence_frequency_measure,metric_params={'value_counts_dict':value_counts_dict}).fit(df2_cp[:1000,])
result2_arr=neighbor_iofm.kneighbors()


Ta có result1_arr là 1 tuple gồm 2 ma trận, với ma trận đầu tiên là khoảng cách từ mỗi điểm đến k điểm gần nhất , ma trận thứ hai tương ứng là index của các điểm gần nhất đó

In [290]:
print(result2_arr[1])
print(result2_arr[0])

[[ 14  12  11 ...   3   4   1]
 [ 13  15   4 ...  12   6  10]
 [580 453 458 ...  93 541 266]
 ...
 [529 528 527 ... 532 504 531]
 [529 528 527 ... 532 504 531]
 [321 365 323 ... 313 539 319]]
[[  -693.79603563   -693.79603563   -693.79603563 ...   -686.73090254
    -686.73090254   -686.73090254]
 [  -688.62419477   -688.62419477   -688.62419477 ...   -688.62419477
    -688.62419477   -688.62419477]
 [-58578.56796211 -58578.56796211 -58578.56796211 ... -58578.56796211
  -58578.56796211 -58578.56796211]
 ...
 [  -680.87187748   -680.87187748   -680.87187748 ...   -680.87187748
    -680.87187748   -680.87187748]
 [  -680.87187748   -680.87187748   -680.87187748 ...   -680.87187748
    -680.87187748   -680.87187748]
 [ -3006.65991831  -3006.65991831  -3006.65991831 ...  -3006.65991831
   -3006.65991831  -3006.65991831]]


In [291]:
print('k lang gieng gan nhat voi diem 0 : ')
print(result2_arr[1][0,:]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-result2_arr[0][0,:]) # In ra độ đo inverse occurence frequency measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 : 
[14 12 11 16 13 15 17 20 19 21 22 23 24 25 18  5  2  3  4  1]
khoang cach tuong ung
[693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 686.73090254 686.73090254 686.73090254 686.73090254 686.73090254]


Em sẽ kiểm tra lại bằng cách tính trực tiếp

Ở đây em chỉ kiểm tra với khoảng cách lớn nhất (693.79), vì ví dụ như có nhiều hơn k điểm với khoảng cách là như nhau, thì khi lấy k điểm láng giềng có thể sẽ khác nhau

Ví dụ như có 3 điểm (1, 2, 3 ) có khoảng cách bằng nhau tới điểm 0 , thì khi lấy 2 láng giềng của điểm 0 thì có thể là (1, 2) ,(2, 3) hay (1, 3)

In [292]:
print('k lang gieng gan nhat voi diem 0 : ')
print(np.argsort(np.array([inverse_occurrence_frequency_measure(df2_cp[0,:],df2_cp[i],value_counts_dict) for i in range(0,1000)]))[1:21]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-np.sort(np.array([inverse_occurrence_frequency_measure(df2_cp[0,:],df2_cp[i,:],value_counts_dict) for i in range(0,1000)]))[1:21]) # In ra độ đo inverse occurence frequency measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 : 
[25 24 23 21 20 19 18 17 16 15 14 13 22 11 12  1  3  4  5  2]
khoang cach tuong ung
[693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 686.73090254 686.73090254 686.73090254 686.73090254 686.73090254]


Kết quả kiểm tra 15 điểm gần với 0 nhất với khoảng cách là 37 là : 25 24 23 21 20 19 18 17 16 15 14 13 22 11 12

## Bonus

Có thể dùng PCA để giảm chiều dữ liệu xuống , khi đó tính khoảng cách sẽ nhanh hơn ạ